baseURL: "https://theoretickles.netlify.app/"
languageCode: en-us
title: Theoretickles
theme: "PaperMod"
pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

build:
  noJSConfigInAssets: false
  useResourceCacheWhen: fallback
  writeStats: false

outputs:
  home:
    - HTML
    - RSS # is necessary for rss
    - JSON # is necessary for search

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Theoreticles
  description: "A blog on Quantum Computing and Theoretical Computer Science"
  keywords:
    [Quantum, Computer Science, Machine Learning, Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowRelatedContent: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  math: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Theoretickles"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Welcome to Theoreticles
    subtitle: "A collection of essays on various topics in Theoretical CS that tickle my fancy!"
    imageUrl: "dp.jpg"
    imageWidth: 400
    imageHeight: 400
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: search
        url: "/search"
      - name: archive
        url: "/archives"

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B Welcome to Theoretickles"
    Content: A collection of essays on various topics in Theoretical CS that tickle my fancy!!

  socialIcons:
    - name: twitter
      url: "https://twitter.com/chatsagnik"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/chatsagnik"
    - name: "rss"
      url: "https://theoretickles.netlify.app/index.xml"
    - name: "Personal website"
      url: "https://chatsagnik.github.io/"
    - name: "Bluesky"
      url: "https://bsky.app/profile/chatsagnik.bsky.social"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    includeMatches: true
    location: 0
    distance: 1000
    threshold: 0.2
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
taxonomies:
  tag: tags
  category: categories
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: home
      name: chatsagnik
      url: https://chatsagnik.github.io
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
    - identifier: archives
      name: archives
      url: /archives/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
